### PR TITLE
Fix CPU query

### PR DESCRIPTION
**Pull request by csibbitt**
Closes https://github.com/infrawatch/dashboards/issues/55

### CODE REVIEW

**Comment by csibbitt** [comment]
image
Here is a test of the query. The original query said my controller-0 CPU was at 28.4799%. The revised query says 99.9999%.

```
[root@controller-0 ~]# uptime
 13:56:00 up 13 days, 16:02,  1 user,  load average: 14.14, 12.73, 12.56
```

Yup, that's 99.9999% alright.

Ideally we should test the dashboard itself and the multi-host scenario.

**Review by leifmadsen — APPROVED** [review]
I trust your testing methods, and the query looks sane. I have not independently verified this.

I think we're going to also want a small documentation update to indicate that the query changed. This would simply be in the release notes.

**Comment by csibbitt** [comment]
I'm not going to merge this until I have (or someone has) loaded the dashboard in grafana and selected multiple hosts. I'll likely be able to fit it in over the next couple days, but don't currently have a grafana deployment

**Comment by leifmadsen** [comment]
> I'm not going to merge this until I have (or someone has) loaded the dashboard in grafana and selected multiple hosts. I'll likely be able to fit it in over the next couple days, but don't currently have a grafana deployment

I think this is something I can load into my environment which is running Grafana as part of other development. Victoria also noted she might have an OSP environment (I also have one) so we can point both our deployments at my STF environment and I can load the updated dashboard.

**Comment by leifmadsen** [comment]
Sorry, do you want to see multiple clouds, or multiple infrastructure nodes?

Here are a couple of screenshots from New vs Original, comparing controller vs compute nodes.

**compute-1**

_Original_
image

_Update_
image

**controller-0**

_Original_
image

_Update_
image

**Comment by csibbitt** [comment]
The `sum by (host,plugin_instance)` and the naming of the variable `$hosts` led me to believe that it was possible to multi-select more than one host for this query. If that's not the case, then this is good enough.

**Comment by leifmadsen** [comment]
> The `sum by (host,plugin_instance)` and the naming of the variable `$hosts` led me to believe that it was possible to multi-select more than one host for this query. If that's not the case, then this is good enough.

Ah gotcha. I think our dashboards only play in single selector drop down and not a multi-select box as it stands.

**Pull request merged**
