### PR TITLE
Add Smart Gateway Tracker dashboard

### PR DESCRIPTION
**Pull request by leifmadsen**
Provides a dashboard for tracking message ingestion by Smart Gateways in STF 1.3.

### CODE REVIEW

**Comment by leifmadsen** [comment]
image

**Comment by leifmadsen** [comment]
Of particular review, I'd like this query verified as sane and correct:

```json
      "expr": "(sg_total_collectd_metric_decode_count + sg_total_collectd_metric_decode_error_count) / sg_total_collectd_metric_decode_count",
```

**Comment by pleimer** [comment]
> Of particular review, I'd like this query verified as sane and correct:
> 
> ```yaml
>       "expr": "(sg_total_collectd_metric_decode_count + sg_total_collectd_metric_decode_error_count) / sg_total_collectd_metric_decode_count",
> ```

Based on how sg-core accumulates those numbers, that should be correct

**Review by pleimer — APPROVED** [review]

**Comment by csibbitt** [comment]
> > Of particular review, I'd like this query verified as sane and correct:
> > ```yaml
> >       "expr": "(sg_total_collectd_metric_decode_count + sg_total_collectd_metric_decode_error_count) / sg_total_collectd_metric_decode_count",
> > ```
> 
> Based on how sg-core accumulates those numbers, that should be correct

Not sure I agree. Looking at the code, it seems that either the total count gets incremented OR the error count (not both), so if you want a % decoded or a % error, you should have `(sg_total_collectd_metric_decode_count + sg_total_collectd_metric_decode_error_count)` in your denominator, not the numerator. 

Consider 100 messages with 20 decode errors. 

The current formula labelled "Collectd Metric Decoding Percentage" would give `(80 + 20) / 80 = 125%`

I think you want `sg_total_collectd_metric_decode_count  / ( sg_total_collectd_metric_decode_count + sg_total_collectd_metric_decode_error_count)` which would give `80 / (80 + 20) = 80%`

Did I misunderstand the code?

**Comment by pleimer** [comment]
Nope, you are correct! I misread the query, thanks for checking

**Review by pleimer — APPROVED** [review]

**Pull request merged**
